### ISSUE TITLE
Email activation process

### ISSUE THREAD

**Issue by ngrebenshikov** [abakan-student-projects/scholae-web#37]
1. A user sends the registration form
2. The system creates a user account and sends a greeting email to user.
3. The system send the email activation email to user with an activation link.
4. A user goes via the activation link and the system stores that email and user account are fully activated.
4.1 If user didn't activate email for a week and tries to access the system the system will not give him login to the system.

1 and 2 already implemented. See LearnerService.registerAndAuthenticateUser on the server side. See also server-shared/model/User. It already has the fields you need:    
public var registrationDate: SDateTime;
    public var emailActivationCode: SString<128>;
    public var emailActivated: SBool;

**Comment by aleksandrvergunov** [comment]
I made a beta version, and i have a question. If you make clause 4.1, then an authorization problem occurs after registration, that is, it turns out that only an authorized user can log in to the system, and because of this, an error occurs after registration. I made it possible to activate the e-mail within 7 days, but did not prohibit authorization after registration, if the e-mail is not confirmed ... Do I have to do this? It is necessary to rewrite the code.

**Comment by ngrebenshikov** [comment]
Two issues:
- [ ] A user should be able activate email anytime. But a user shouldn't be able to login without activate after 7 days.
- [ ] https://api.haxe.org/DateTools.html#delta can be used fo adding 7 days. It's better to use it instead of the date parsing.
